import React, { useCallback, useEffect } from 'react'
import DashboardLayout from '../layouts/DashboardLayout'
import PageHead from '../components/PageHead'
import CommonDataTable from '../components/CommonDataTable'
import ActivityLogService from '../services/ActivityLogService'
import useTable from '../libraries/handleTable'
import { isoToDateTime } from '../libraries/common'
import StatusBadge from '../components/StatusBadge'
import { useI18n } from '../../i18n/useI18n'

export default function ActivityLogs() {
    const { t } = useI18n()
    const table = useTable()

    const getLogs = useCallback((page = 0) => {
        table.setLoading(true)
        ActivityLogService.list({ page })
            .then((resp) => {
                table.setLoading(false)
                table.setData(resp.message.data)
                table.setLinks(resp.message.links)
            })
            .catch(() => {})
    }, [])

    useEffect(() => {
        getLogs()
    }, [])

    return (
        <DashboardLayout>
            <div>
                <PageHead
                    title={t('Activity logs')}
                    subtitle={t(
                        'Manage all system logs generated by user actions'
                    )}
                />

                <div className="container mt-3">
                    <CommonDataTable
                        movePage={getLogs}
                        loading={table.loading}
                        data={table.data}
                        links={table.links}
                        columns={[
                            { key: 'id', label: t('ID') },
                            {
                                key: 'action',
                                label: t('Action'),
                                render: (action) => (
                                    <StatusBadge status={action} />
                                ),
                            },
                            {
                                key: 'description',
                                label: t('Description'),
                            },
                            {
                                key: 'entity_type',
                                label: t('Entity type'),
                            },
                            {
                                key: 'entity_id',
                                label: t('Entity ID'),
                            },
                            {
                                key: 'created_at',
                                label: t('Created at'),
                                render: (time) => (
                                    <span>{isoToDateTime(time)}</span>
                                ),
                            },
                        ]}
                    />
                </div>
            </div>
        </DashboardLayout>
    )
}
