<?php

return [
    'countries' => [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bangladesh',
        'Belarus',
        'Belgium',
        'Bolivia',
        'Brazil',
        'Bulgaria',
        'Cambodia',
        'Canada',
        'Chile',
        'China',
        'Colombia',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Czech Republic',
        'Denmark',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Japan',
        'Kazakhstan',
        'Kenya',
        'Laos',
        'Latvia',
        'Lithuania',
        'Luxembourg',
        'Malaysia',
        'Mexico',
        'Mongolia',
        'Myanmar',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nigeria',
        'North Korea',
        'Norway',
        'Pakistan',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Saudi Arabia',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'South Africa',
        'South Korea',
        'Spain',
        'Sri Lanka',
        'Sweden',
        'Switzerland',
        'Thailand',
        'Turkey',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Vietnam',
    ]
];
